### ISSUE TITLE
Getting color to behave on the map

### ISSUE THREAD

**Issue by daleinen7** [Code-For-Chicago/greater-chicago-food-despository-ui#102]
Here is what I know/remember. 

There was a ticket started by one person to get the color of the key and the map itself to relate to the donut data. I don't know how far they got, but they had to leave the project, so someone else took over. And eventually they turned the data from pulling from the back end to just pull from JSON files. Then they got it mostly working, but going to WIC and Snap would crash the site. 

Then they had to leave the project. 

So I eventually got it to not crash. And then because the PR was so old, trying to merge it back with main broke the original functionality as well as other features (most notably the counties wouldn't outline on hover). Ryan then took a look at it, and got a lot of the functionality back. And so now it's where it is ... the color isn't quite matching the data, the names of the counties etc, are not on the map.

**Comment by brickman1444** [comment]
Closed by https://github.com/Code-For-Chicago/greater-chicago-food-despository-ui/pull/104
