### ISSUE TITLE
Incorporate Data into GeoJSON Files

### ISSUE THREAD

**Issue by egabrielse** [Code-For-Chicago/greater-chicago-food-despository-ui#8]
Prerequisite: May need to wait for state-management to be setup.

Task: Fetch the data and store it in state. 
Looks like there are four JSON files to add.

Data as JSON files can be found in this folder:
https://drive.google.com/drive/folders/1VooXgKz0-RVLNYy_NKHxvHb15zJUxzbL

Format for the data can be found in the README for the frontend.

**Comment by mcdevittbass** [comment]
GeoJSON files are currently stored in the state.

Current issue: decide when to get other data files:
Option 1: get all data on load and store in Redux store
Option 2: only get specific county and/or zip data when area is clicked or hovered over (this does not include bins for each metric which will be incorporated into the GeoJSON for use in styling the map)
Option 3: ?
